name: trax
description: Music management for all!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async_task: ^1.0.20
  cupertino_icons: ^1.0.2
  easy_isolate: ^1.3.0
  intl: any
  macos_ui:
    git:
      url: https://github.com/nbonamy/macos_ui
      ref: autocomplete
  contextual_menu:
    git:
      url: https://github.com/nbonamy/contextual_menu
  audiotranscode_ffi: ^1.3.0
  cached_network_image: ^3.2.3
  desktop_drop: ^0.4.1
  event_bus: ^2.0.0
  extended_wrap: ^0.1.5
  file_picker: ^5.2.7
  http: ^0.13.5
  just_audio_background: ^0.0.1-beta.9
  just_audio: ^0.9.32
  loading_animation_widget: ^1.2.0+4
  logger: ^1.3.0
  mutex: ^3.0.1
  pasteboard: ^0.2.0
  path_provider: ^2.0.14
  path: ^1.8.2
  provider: ^6.0.2
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.15
  sqflite: ^2.2.6
  taglib_ffi: ^0.1.0
  window_manager: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - graphics/app_icon.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
