import 'dart:ui';

class Consts {
  static const double fadedOpacity = 0.4;

  static const Color sideBarBgColor = Color.fromRGBO(241, 235, 230, 1.0);
  //static const Color sideBarFgColor = const Color.fromRGBO(177, 171, 166, 1.0);
  static const Color sideBarSelectColor = Color.fromRGBO(216, 210, 205, 1.0);

  static const List<String> genres = [
    '',
    'A Cappella',
    'Abstract',
    'Acid Jazz',
    'Acid Punk',
    'Acid',
    'Acoustic',
    'Alternative Rock',
    'Alternative',
    'Ambient',
    'Anime',
    'Art Rock',
    'Audio Theatre',
    'Audiobook',
    'Avant-garde',
    'Ballad',
    'Baroque',
    'Bass',
    'Beat',
    'Bebop',
    'Bhangra',
    'Big Band',
    'Big Beat',
    'Black Meta',
    'Bluegrass',
    'Blues',
    'Booty Bass',
    'Breakbeat',
    'Britpop',
    'Cabaret',
    'Celtic',
    'Chamber Music',
    'Chanson',
    'Chillout',
    'Chorus',
    'Christian Gangsta Rap',
    'Christian Rap',
    'Christian Rock',
    'Classic Rock',
    'Classica',
    'Club-House',
    'Club',
    'Comedy',
    'Contemporary Christian',
    'Country',
    'Crossover',
    'Cult',
    'Dance',
    'Dancehal',
    'Darkwave',
    'Death Meta',
    'Disco',
    'Downtempo',
    'Dream',
    'Drum & Bass',
    'Drum Solo',
    'Dub',
    'Dubstep',
    'Duet',
    'Easy Listening',
    'EBM',
    'Eclectic',
    'Electro',
    'Electroclash',
    'Electronic',
    'Emo',
    'Ethnic',
    'Euro-House',
    'Euro-Techno',
    'Eurodance',
    'Experimenta',
    'Fast Fusion',
    'Folk Rock',
    'Folk',
    'Folklore',
    'Freestyle',
    'Funk',
    'Fusion',
    'G-Funk',
    'Game',
    'Gangsta',
    'Garage Rock',
    'Garage',
    'Globa',
    'Goa',
    'Gospe',
    'Gothic Rock',
    'Gothic',
    'Grunge',
    'Hard Rock',
    'Hardcore Techno',
    'Heavy Meta',
    'Hip-Hop',
    'House',
    'Humour',
    'IDM',
    'Illbient',
    'Indie Rock',
    'Indie',
    'Industria',
    'Industro-Goth',
    'Instrumenta',
    'Instrumental Pop',
    'Instrumental Rock',
    'Jam Band',
    'Jazz-Funk',
    'Jazz',
    'Jpop',
    'Jungle',
    'Krautrock',
    'Latin',
    'Leftfield',
    'Lo-Fi',
    'Lounge',
    'Math Rock',
    'Meditative',
    'Merengue',
    'Meta',
    'Musica',
    'National Folk',
    'Native American',
    'Neoclassica',
    'Neue Deutsche Welle',
    'New Age',
    'New Romantic',
    'New Wave',
    'Noise',
    'Nu-Breakz',
    'Oldies',
    'Opera',
    'Other',
    'Podcast',
    'Polka',
    'Polsk Punk',
    'Pop-Folk',
    'Pop',
    'Pop/Funk',
    'Porn Groove',
    'Post-Punk',
    'Post-Rock',
    'Power Ballad',
    'Pranks',
    'Primus',
    'Progressive Rock',
    'Psybient',
    'Psychedelic Rock',
    'Psychedelic',
    'Psytrance',
    'Punk Rock',
    'Punk',
    'R&B',
    'Rap',
    'Rave',
    'Reggae',
    'Retro',
    'Reviva',
    'Rhythmic Sou',
    'Rock & Rol',
    'Rock',
    'Salsa',
    'Samba',
    'Satire',
    'Shoegaze',
    'Showtunes',
    'Ska',
    'Slow Jam',
    'Slow Rock',
    'Sonata',
    'Sou',
    'Sound Clip',
    'Soundtrack',
    'Southern Rock',
    'Space Rock',
    'Space',
    'Speech',
    'Swing',
    'Symphonic Rock',
    'Symphony',
    'Synthpop',
    'Tango',
    'Techno-Industria',
    'Techno',
    'Terror',
    'Thrash Meta',
    'Top 40',
    'Trailer',
    'Trance',
    'Triba',
    'Trip-Hop',
    'Trop Rock',
    'Voca',
    'World Music',
    'Worldbeat',
  ];
}
